import { useEffect, useState } from 'react'
import type { FormEvent } from 'react'
import { api, money, today } from './api'
import { dateLabel, supplyForecast } from '../shared/household'
import type { SupplyItem, SupplyPurchase, SupplyOperation } from '../shared/household'
import { defaultOperationCategories } from '../shared/operationCategories'
import { HouseholdStatus, send, useHouseholdAction } from './household-ui'
import './household.css'
const blankItem = (): Omit<SupplyItem, 'id'> => ({ name: '', details: '', category: 'Для дома', intervalDays: null, runningLow: false })
type PurchaseForm = { id?: string; itemId: string; date: string; amount: string; quantity: string; note: string; finance: 'none' | 'create' | 'link'; operationId: string; linked: boolean }
export default function Supplies() {
  const [items, setItems] = useState<SupplyItem[]>([]), [purchases, setPurchases] = useState<SupplyPurchase[]>([]), [operations,setOperations] = useState<SupplyOperation[]>([]), [customCategories,setCustomCategories] = useState<string[]>([])
  const [loading,setLoading] = useState(true), [loaded,setLoaded] = useState(false)
  const [itemForm,setItemForm] = useState<ReturnType<typeof blankItem> | null>(null), [itemId,setItemId] = useState<string | null>(null), [purchaseForm,setPurchaseForm] = useState<PurchaseForm | null>(null)
  const [filter,setFilter] = useState(''), [status,setStatus] = useState('all')
  const { busy,error,run } = useHouseholdAction(), now = today(), disabled = busy || !loaded
  useEffect(() => { if (itemForm || purchaseForm) document.querySelector('.household-editor')?.scrollIntoView({ block: 'start', behavior: 'smooth' }) }, [!!itemForm, !!purchaseForm])
  async function load() {
    const [i,p,o,c] = await Promise.all([api<SupplyItem[]>('/api/supplies/items'),api<SupplyPurchase[]>('/api/supplies/purchases'),api<SupplyOperation[]>('/api/expenses'),api<{name:string;type:string}[]>('/api/operation-categories')])
    setItems(i); setPurchases(p); setOperations(o); setCustomCategories(c.filter((x) => x.type === 'expense').map((x) => x.name)); setLoaded(true)
  }
  useEffect(() => { void run(async () => { try { await load() } finally { setLoading(false) } }) }, [])
  const forecasts = new Map(items.map((i) => [i.id,supplyForecast(i,purchases,now)]))
  const upcoming = (item: SupplyItem) => { const date = forecasts.get(item.id)?.nextDate; return item.runningLow || !!date && date <= new Date(Date.parse(`${now}T00:00:00Z`) + 30 * 86400000).toISOString().slice(0,10) }
  const reserve = [...forecasts.values()].reduce((sum,f) => sum + (f.monthlyReserve ?? 0),0)
  const estimatesCount = [...forecasts.values()].filter((f) => f.monthlyReserve !== null).length
  const visible = items.filter((i) => (!filter || filter === i.id) && (status === 'all' || status === 'low' && i.runningLow || status === 'upcoming' && upcoming(i)))
  function editItem(item?: SupplyItem) { setItemId(item?.id ?? null); setItemForm(item ?? blankItem()); setPurchaseForm(null) }
  function openPurchase(item: SupplyItem, purchase?: SupplyPurchase) {
    setItemForm(null)
    setPurchaseForm({ id: purchase?.id, itemId: item.id, date: purchase?.date ?? now, amount: purchase ? String(purchase.amount) : '', quantity: purchase?.quantity ?? '', note: purchase?.note ?? '', finance: purchase?.operationId ? purchase.ownsOperation ? 'create' : 'link' : purchase ? 'none' : 'create', operationId: purchase?.operationId ?? '', linked: !!purchase?.operationId })
  }
  function submitItem(e: FormEvent) {
    e.preventDefault(); void run(async () => { await send(`/api/supplies/items${itemId ? `/${itemId}` : ''}`,itemId ? 'PUT' : 'POST',itemForm); setItemForm(null); await load() })
  }
  function submitPurchase(e: FormEvent) {
    e.preventDefault(); if (!purchaseForm) return
    void run(async () => { await send(`/api/supplies/purchases${purchaseForm.id ? `/${purchaseForm.id}` : ''}`,purchaseForm.id ? 'PUT' : 'POST',{ ...purchaseForm, amount: Number(purchaseForm.amount) }); setPurchaseForm(null); await load() })
  }
  function toggleLow(item: SupplyItem) { void run(async () => { await send(`/api/supplies/items/${item.id}`,'PUT',{ ...item,runningLow: !item.runningLow }); await load() }) }
  function removeItem(item: SupplyItem) {
    if (!confirm(`Удалить запас «${item.name}» и историю покупок? Денежные расходы сохранятся в «Операциях».`)) return
    void run(async () => { await send(`/api/supplies/items/${item.id}`,'DELETE'); if (filter === item.id) setFilter(''); await load() })
  }
  function removePurchase(p: SupplyPurchase, deleteExpense: boolean) {
    if (!confirm(deleteExpense ? 'Удалить покупку вместе с созданным расходом? Остаток денег изменится.' : 'Удалить запись покупки? Связанный денежный расход сохранится.')) return
    void run(async () => { await send(`/api/supplies/purchases/${p.id}${deleteExpense ? '?deleteExpense=true' : ''}`,'DELETE'); await load() })
  }
  const categoryOptions = [...new Set([...defaultOperationCategories.expense,...customCategories,...items.map((i) => i.category),...operations.filter((o) => o.type === 'expense').map((o) => o.category)])]
  const linkedIds = new Set(purchases.filter((p) => p.operationId && p.id !== purchaseForm?.id).map((p) => p.operationId))
  const availableOperations = operations.filter((o) => o.type === 'expense' && o.date <= now && !linkedIds.has(o.id))
  const externalLink = purchaseForm?.finance === 'link'
  return <main className="household-page">
    <header><div><div className="eyebrow">ДОМ И ПОКУПКИ</div><h1>Запасы</h1><p className="muted">Редкие покупки: когда покупал, сколько потратил и когда могут понадобиться снова.</p></div><button disabled={disabled} onClick={() => editItem()}>+ Запас</button></header>
    <HouseholdStatus loading={loading} error={error} />
    {loaded && <section className="card household-summary"><div><small>Откладывать на месяц</small><strong>{estimatesCount ? money(reserve) : 'Пока нет оценки'}</strong><p className="muted">Ориентир по {estimatesCount} из {items.length} запасов. Это план накоплений; сумма не списывается и не меняет остаток.</p></div><div><small>Ближайшие покупки</small><strong>{items.filter(upcoming).length}</strong><p className="muted">Заканчиваются или ожидаются в следующие 30 дней.</p></div></section>}
    {itemForm && <section className="card household-editor"><h2>{itemId ? 'Изменить запас' : 'Новый запас'}</h2><form onSubmit={submitItem}><fieldset disabled={busy}><div className="household-fields"><label>Название<input autoFocus required maxLength={100} value={itemForm.name} onChange={(e) => setItemForm({ ...itemForm,name:e.target.value })} placeholder="Кофе" /></label><label>Описание<input maxLength={250} value={itemForm.details} onChange={(e) => setItemForm({ ...itemForm,details:e.target.value })} placeholder="Марка, привычная упаковка…" /></label><label>Категория расхода<input required list="supply-categories" maxLength={100} value={itemForm.category} onChange={(e) => setItemForm({ ...itemForm,category:e.target.value })} /><datalist id="supply-categories">{categoryOptions.map((c) => <option key={c} value={c} />)}</datalist></label><label>Обычно хватает на, дней<input type="number" min={1} max={3650} value={itemForm.intervalDays ?? ''} onChange={(e) => setItemForm({ ...itemForm,intervalDays:e.target.value ? Number(e.target.value) : null })} placeholder="Пока неизвестно" /></label></div><label className="household-select"><input type="checkbox" checked={itemForm.runningLow} onChange={(e) => setItemForm({ ...itemForm,runningLow:e.target.checked })} />Заканчивается</label><p className="muted">Срок приблизительный. Можно оставить пустым и задать позже.</p><div className="household-actions"><button type="submit">Сохранить</button><button type="button" className="secondary" onClick={() => setItemForm(null)}>Отмена</button></div></fieldset></form></section>}
    {purchaseForm && <section className="card household-editor"><h2>{purchaseForm.id ? 'Изменить покупку' : 'Купил'} · {items.find((i) => i.id === purchaseForm.itemId)?.name}</h2><form onSubmit={submitPurchase}><fieldset disabled={busy}><label>Учёт денег<select disabled={purchaseForm.linked} value={purchaseForm.finance} onChange={(e) => setPurchaseForm({ ...purchaseForm,finance:e.target.value as PurchaseForm['finance'],operationId:'' })}><option value="create">{purchaseForm.id && purchaseForm.linked ? 'Обновить связанный расход' : 'Создать расход в «Операциях»'}</option><option value="link">Привязать существующий расход</option><option value="none">Только история покупки</option></select></label>
      {externalLink && <label>Расход<select required disabled={purchaseForm.linked} value={purchaseForm.operationId} onChange={(e) => { const op = operations.find((o) => o.id === e.target.value); setPurchaseForm({ ...purchaseForm,operationId:e.target.value,date:op?.date ?? now,amount:op ? String(op.amount) : '' }) }}><option value="">Выбери расход</option>{availableOperations.map((o) => <option key={o.id} value={o.id}>{dateLabel(o.date)} · {o.title} · {money(o.amount)}</option>)}</select></label>}
      <div className="household-fields"><label>Дата<input autoFocus type="date" required disabled={externalLink} min="1900-01-01" max={now} value={purchaseForm.date} onChange={(e) => setPurchaseForm({ ...purchaseForm,date:e.target.value })} /></label><label>Стоимость, ₽<input type="number" required disabled={externalLink} min="0.01" max="999999999.99" step="0.01" value={purchaseForm.amount} onChange={(e) => setPurchaseForm({ ...purchaseForm,amount:e.target.value })} /></label><label>Количество / упаковка<input maxLength={120} value={purchaseForm.quantity} onChange={(e) => setPurchaseForm({ ...purchaseForm,quantity:e.target.value })} placeholder="1 кг, 2 флакона…" /></label><label>Комментарий<input maxLength={500} value={purchaseForm.note} onChange={(e) => setPurchaseForm({ ...purchaseForm,note:e.target.value })} /></label></div>
      <p className="muted">{externalLink ? 'Сумма и дата берутся из выбранного расхода. Их изменения в «Операциях» отразятся здесь.' : purchaseForm.finance === 'create' ? 'Покупка и расход сохранятся вместе. Отдельно записывать эту трату не нужно.' : 'Запись не изменит денежный остаток.'} После сохранения отметка «Заканчивается» снимается.</p><div className="household-actions"><button type="submit">Сохранить покупку</button><button type="button" className="secondary" onClick={() => setPurchaseForm(null)}>Отмена</button></div></fieldset></form></section>}
    <div className="household-toolbar"><label>Показать запас<select value={filter} onChange={(e) => setFilter(e.target.value)}><option value="">Все запасы</option>{items.map((i) => <option key={i.id} value={i.id}>{i.name}</option>)}</select></label><label>Состояние<select value={status} onChange={(e) => setStatus(e.target.value)}><option value="all">Все</option><option value="low">Заканчиваются</option><option value="upcoming">Ближайшие покупки</option></select></label></div>
    <div className="household-grid">{visible.map((i) => { const f = forecasts.get(i.id)!; return <article className="card household-item" key={i.id}><div className="household-item-heading"><h2>{i.name}</h2>{i.runningLow && <span className="household-reminder">Заканчивается</span>}</div>{i.details && <p className="muted">{i.details}</p>}<p>{f.last ? <>Последняя покупка <strong>{dateLabel(f.last.date)}</strong><small className="household-meta">{money(f.last.amount)}{f.last.quantity && ` · ${f.last.quantity}`}</small></> : 'Покупок пока нет'}</p><p>{f.nextDate ? `Следующая — примерно ${dateLabel(f.nextDate)}` : 'Срок следующей покупки неизвестен'}{f.monthlyReserve !== null && <small className="household-meta">Откладывать около {money(f.monthlyReserve)} / мес.</small>}</p>{!i.intervalDays && f.suggestedDays && <p className="muted">По истории покупал примерно раз в {f.suggestedDays} дн. <button className="link-button" disabled={disabled} onClick={() => { setItemId(i.id); setItemForm({ ...i,intervalDays:f.suggestedDays }); setPurchaseForm(null) }}>Использовать срок</button></p>}<div className="household-actions"><button disabled={disabled} onClick={() => openPurchase(i)}>Купил</button><button className="secondary" disabled={disabled} onClick={() => toggleLow(i)}>{i.runningLow ? 'Есть в запасе' : 'Заканчивается'}</button><button className="secondary" disabled={disabled} onClick={() => editItem(i)}>Изменить</button><button className="icon-button delete" disabled={disabled} aria-label={`Удалить запас ${i.name}`} onClick={() => removeItem(i)}>×</button></div></article> })}</div>
    {!loading && loaded && !visible.length && <section className="card empty"><h2>{items.length ? 'В этом списке пока пусто' : 'Добавь первую редкую покупку'}</h2><p className="muted">{items.length ? 'Измени фильтр или отметь запас как заканчивающийся.' : 'Например: кофе, шампунь, гель для душа или стиральный порошок.'}</p></section>}
    {!!purchases.length && <section className="card household-history"><h2>История покупок</h2>{purchases.filter((p) => !filter || p.itemId === filter).map((p) => <div className="household-history-row" key={p.id}><div><strong>{items.find((i) => i.id === p.itemId)?.name} · {money(p.amount)}</strong><small>{dateLabel(p.date)}{p.quantity && ` · ${p.quantity}`}{p.note && ` · ${p.note}`}</small><small>{p.operationId ? `Связано с расходом · ${p.category}` : 'Только история, без денежной операции'}</small></div><div className="household-actions"><button className="secondary" disabled={disabled} onClick={() => openPurchase(items.find((i) => i.id === p.itemId)!,p)}>Изменить</button><button className="secondary" disabled={disabled} onClick={() => removePurchase(p,false)}>Удалить запись</button>{p.ownsOperation && <button className="secondary" disabled={disabled} onClick={() => removePurchase(p,true)}>Удалить с расходом</button>}</div></div>)}</section>}
  </main>
}
